name: development

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]
  workflow_dispatch:


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: "echo Hello"